# Generated by Django 4.2.1 on 2023-05-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_estacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='peiodo',
            new_name='periodo',
        ),
    ]
